### ISSUE TITLE
Guard against format requests for files that don't yet exist on disk

### ISSUE THREAD

**Issue by xeger** [ruby-syntax-tree/syntax_tree#102]
Steps to reproduce:
1) Install vscode-syntax-tree & make sure it's in working order on existing source files
2) Use `code foo.rb` to open a buffer with a name, on a file that doesn't yet exist on disk
3) Type some Ruby code into the buffer to trigger a `textDocument/inlayHints` request

Outcome: the `stree` process crashes with `ENOENT`

Desired: the process recovers from file-not-exist (either by failing the jsonrpc request, or perhaps by grabbing fresh content from the request and putting it into the store).

Full backtrace here:
```
<snip>/syntax_tree-2.8.0/lib/syntax_tree/language_server.rb:26:in `binread': No such file or directory @ rb_sysopen - /tmp/bar.rb (Errno::ENOENT)
	from <snip>/syntax_tree-2.8.0/lib/syntax_tree/language_server.rb:26:in `block in run'
	from <snip>/syntax_tree-2.8.0/lib/syntax_tree/language_server.rb:68:in `run'
	from <snip>/syntax_tree-2.8.0/lib/syntax_tree/cli.rb:262:in `run'
	from <snip>/syntax_tree-2.8.0/exe/stree:9:in `<top (required)>'
```

**Comment by kddnewton** [comment]
Tangential but related to this is #103, because that should make it so that these requests never get fired in the first place.
