### ISSUE TITLE
Rework inlay hints to match the spec

### ISSUE THREAD

**Issue by kddnewton** [ruby-syntax-tree/syntax_tree#103]
At the time that I wrote the inlay hints stuff for the language server, inlay hints were not actually a part of the LSP. Since then, they have been added. If we conform to the spec, we can greatly simplify vscode-syntax-tree because it won't have to handle deduping itself and can just let the client handle it. Additionally, it will work for clients that aren't vscode.

**Comment by xeger** [comment]
[Link to spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) for those who are curious. I'm familiarizing myself with it to see how difficult this might be.
