### ISSUE TITLE
Support for Ruby 2.7.0?

### ISSUE THREAD

**Issue by raxod502** [ruby-syntax-tree/syntax_tree#144]
I am trying to install Prettier for Ruby on Ubuntu 20.04 LTS. Unfortunately, since that version of Ubuntu ships Ruby 2.7.0 while syntax_tree (a dependency of the prettier gem) has a minimum requirement of 2.7.3 (https://github.com/ruby-syntax-tree/syntax_tree/issues/14), it doesn't work.

Is support for 2.7.0 something that might be considered supposing that somebody puts in the effort for a PR?

**Comment by kddnewton** [comment]
Okay, we now support back to 2.7.0, I'll release momentarily.
