### ISSUE TITLE
Rightward assignment `=>` converted to `in` when preceded by `in` in a prior line

### ISSUE THREAD

**Issue by nixme** [ruby-syntax-tree/syntax_tree#146]
Example:

```ruby
puts SyntaxTree.format <<~RUBY
  if a in Integer
    puts "a is integer"
  end

  b => [Integer => c]
RUBY
```

emits:

```ruby
puts "a is integer" if a in Integer

b in [Integer => c]
```

---

However, as long as you don't use `in` earlier in scope, the `b` line correctly isn't modified

```ruby
puts SyntaxTree.format "b => [Integer => c]"
```

emits

```ruby
b => [Integer => c]
````

Happy to take a crack at fixing if you can point me in the right direction.

**Comment by kddnewton** [comment]
Thanks for the report! This was actually pretty in the weeds of how the parser works so I went ahead and fixed it myself. The PR is linked, and it'll be out in the next release.
