### ISSUE TITLE
Feature Request: Format the Gemfile

### ISSUE THREAD

**Issue by Petercopter** [ruby-syntax-tree/syntax_tree#155]
Would it be within the scope of syntax_tree to format the Gemfile? I swear at one point prettier-ruby was doing it, but I could be going crazy.

**Comment by kddnewton** [comment]
Not out of scope at all! You can pass `stree write Gemfile` if you want, or you can configure the rake task to include it per the README.

**Comment by Petercopter** [comment]
Hey sorry I should have specified that I was looking for this functionality in VSCode. I tested passing it through the `.streerc` file, but no dice. 

Also, I would expect it to work out of the box, since the Gemfile is technically a Ruby file, right?

```
--plugins=plugin/single_quotes,haml
--write Gemfile
```

**Comment by kddnewton** [comment]
Ahh I see. Yeah that's an issue for the VSCode extension.
