### ISSUE TITLE
Rubymine Integration

### ISSUE THREAD

**Issue by Djiit** [ruby-syntax-tree/syntax_tree#188]
Hey,

What would be the best way to integrate this with RubyMine ?

i.e. be able to format on save.

Thanks

**Comment by kddnewton** [comment]
That's a great question, I don't know! I haven't used RubyMine before. Based on some initial googling it looks like https://plugins.jetbrains.com/plugin/10209-lsp-support might be what you want? You would need something to communicate with the syntax tree language server.

**Comment by kddnewton** [comment]
I'm going to close this issue for now since I don't have any capacity to work on the rubymine plugin. If someone else wants to take a crack at it, I'd be happy to include a link to it on the README!
