### ISSUE TITLE
v5 not using provided plugins

### ISSUE THREAD

**Issue by Djiit** [ruby-syntax-tree/syntax_tree#196]
Hey,

Just FYI, on my machine + our CI, since v5.0.0, our plugins are not respected anymore (in a `.streerc` or via the command line).

**Comment by kddnewton** [comment]
Which plugins are you using?

**Comment by Djiit** [comment]
--plugins=plugin/single_quotes,plugin/trailing_comma

**Comment by kddnewton** [comment]
Sorry about that! Just release v5.0.1

**Comment by Djiit** [comment]
Thanks for the quick action!
