### ISSUE TITLE
`stree format .`? `stree write .`?

### ISSUE THREAD

**Issue by dorianmariefr** [ruby-syntax-tree/syntax_tree#200]
It would be nice to be able to format entire directories

**Comment by kddnewton** [comment]
Yeah, I'm trying to avoid the issue that rubocop has of trying to decide which files to handle. It keeps a list of files that should be formatted, and scans a bunch to find others. I'd rather leave it explicitly up to the consumer. If you're trying to glob things, you probably want `'*.rb'` or `'**/*.rb'`.
