### ISSUE TITLE
Unable to pattern match nodes

### ISSUE THREAD

**Issue by faraazahmad** [ruby-syntax-tree/syntax_tree#219]
I used a class visitor and got the following class
```
(class
  (const_ref (const "HomeController"))
  (var_ref (const "ApplicationController"))
  (bodystmt
    (statements
      ((def
          nil
          nil
          (ident "index")
          (params)
          (bodystmt (statements ((void_stmt)))))))))
```

I tried to use pattern matching on it using
```ruby
case node
in { const_ref: const, var_ref: var, bodystmt: body }
  puts "got class"
end
```

But it didn't match the class. Is there something I'm missing?

**Comment by nvasilevski** [comment]
I may be missing some context and feel free to correct my assumptions, but based on the following:
1. Assuming the source code we are visiting is
```ruby
class HomeController < ApplicationController
  def index
  end
end
```
2. And the goal is to be visiting `ClassDeclaration` nodes

We may use a visitor like:

```ruby
require 'syntax_tree'

class ClassDeclarationVisitor < SyntaxTree::Visitor
  visit_method def visit_class(node)
    if node in SyntaxTree::ClassDeclaration[
        constant: SyntaxTree::ConstRef[constant: SyntaxTree::Const[value: const_name]],
        superclass: SyntaxTree::VarRef[value: SyntaxTree::Const[value: superclass_name]],
        bodystmt: body_statements
        ]

      puts "found class #{const_name} with #{superclass_name} superclass"
    end
  end
end

ClassDeclarationVisitor.new.visit(SyntaxTree.parse(File.read("source.rb")))
```

Which results in 
```
found class HomeController with ApplicationController superclass
```

Generally to get an idea of what pattern matching condition may be used to match again a particular node you can call `.construct_keys` method 
https://github.com/ruby-syntax-tree/syntax_tree/blob/1ebf0a56d1f1a63045074fec948bd3ec7fcbab45/lib/syntax_tree/node.rb#L139 on the node you want to match. 

For example this is what `construct_keys` returns for our `classDeclaration` node:
```
SyntaxTree::ClassDeclaration[
  constant: SyntaxTree::ConstRef[
    constant: SyntaxTree::Const[value: "HomeController"]
  ],
  superclass: SyntaxTree::VarRef[
    value: SyntaxTree::Const[value: "ApplicationController"]
  ],
  bodystmt: SyntaxTree::BodyStmt[
    statements: SyntaxTree::Statements[
      body: [
        SyntaxTree::DefNode[
          target: nil,
          operator: nil,
          name: SyntaxTree::Ident[value: "index"],
          params: SyntaxTree::Params,
          bodystmt: SyntaxTree::BodyStmt[
            statements: SyntaxTree::Statements[body: [SyntaxTree::VoidStmt]]
          ]
        ]
      ]
    ]
  ]
]
```

With pattern matching there will almost always be several ways to match an object and the match condition can be generalized or made more specific. For example in our case matching for `SyntaxTree::ClassDeclaration` should be redundant as I believe every node being visited in the `visit_class` method will be an instance of `ClassDeclaration`

**Comment by kddnewton** [comment]
Hey @faraazahmad!

Ahh I can totally see your confusion. The AST that's returned by that representation gives you the child nodes in order, but doesn't give you the names of the attributes on the parent that give you those nodes. So in your example:

```
(class
  (const_ref (const "HomeController"))
  (var_ref (const "ApplicationController"))
  (bodystmt
    (statements
      ((def
          nil
          nil
          (ident "index")
          (params)
          (bodystmt (statements ((void_stmt)))))))))
```

It would potentially be more clear as:

```
(class
  constant=(const_ref constant=(const value="HomeController"))
  superclass=(var_ref value=(const value="ApplicationController"))
  bodystmt=(bodystmt
    statements=(statements
      body=((def
          target=nil
          operator=nil
          name=(ident value="index")
          params=(params)
          bodystmt=(bodystmt statements=(statements body=((void_stmt)))))))))
```

Sorry for the confusion. It may help to use the `stree match` command to help get your match expression, or to take a look at node.rb in the source here to see the attribute names.
