### ISSUE TITLE
Transformation from `if`...`else` to ternary causes change in behaviour

### ISSUE THREAD

**Issue by davidtaylorhq** [ruby-syntax-tree/syntax_tree#234]
Input:

```ruby
result = if false && val = 1
  "A"
else
  "B"
end
puts result
```
(prints "B" when run)

`stree format` output:

```ruby
result = (false && val = 1 ? "A" : "B")
puts result
```

This prints `false` when run.

It seems that the precedence of the `=` operator is not being considered correctly. It's also curious that the entire ternary expression has been wrapped in parenthesis - they don't seem to have any effect.

The 'correct' output would be for the parenthesis to wrap only the condition part of the ternary:

```ruby
result = (false && val = 1) ? "A" : "B"
```

**Comment by kddnewton** [comment]
Good find! Pushing a fix now
