### ISSUE TITLE
Rightward assignment inside "case ... when" produces invalid syntax

### ISSUE THREAD

**Issue by hpello** [ruby-syntax-tree/syntax_tree#235]
Hey there!

I noticed the following behaviour, when using rightward assignment `=>` inside a `case ... when`:
```ruby
puts SyntaxTree.format <<~RUBY
  case [0]
  when 0
    { a: 0 } => { a: }
    puts a
  end
RUBY
```

produces:

```ruby
[0] =>
  when 0
    case { a: 0 }
    a:
    end
    puts a
```

It seems like the rightward assignment is moved to the top... producing an invalid ruby syntax.
Do you know where this may come from?

Regards,

**Comment by kddnewton** [comment]
Ahh this is a problem with the parser. Just found the fix, thanks!

**Comment by hpello** [comment]
Works like a charm! Thanks 👏🎉
