### ISSUE TITLE
Removing empty parenthesis from method call can change behaviour

### ISSUE THREAD

**Issue by davidtaylorhq** [ruby-syntax-tree/syntax_tree#238]
Input:

```ruby
def string
  "string"
end

string = string()
string += "-appended"

puts string
```

When run, this prints "string-appended"

After formatting, stree removes the parenthesis:

```diff
  def string
    "string"
  end

- string = string()
+ string = string
  string += "-appended"
  
  puts string
```

The resultant script now throws an "undefined method" error

```
test.rb:6:in `<main>': undefined method `+' for nil:NilClass (NoMethodError)

string += "-appended"
       ^
```

(Admittedly this is very strange code, but it is simplified from a [real-world case](https://github.com/discourse/discourse/blob/2644a4d3035f25c9fbdb6a4424153ba09512b931/spec/lib/stylesheet/manager_spec.rb#L264) in Discourse)

**Comment by kddnewton** [comment]
Ahh yeah, I'll fix this.
