### ISSUE TITLE
Avoid converting if/else into long ternary

### ISSUE THREAD

**Issue by gschlager** [ruby-syntax-tree/syntax_tree#243]
The formatter should avoid converting `if/else` into ternary if the the resulting line would be too long. I think stree should disregard the configured `print-width` and use regular `if/else` when the line length of the ternary exceeds ~60 chars.

Original (easy to read):
```ruby
if fits_into_octal?(value, length)
  to_octal(value, length)
else
  to_base256(value, length)
end
```

Formatted with stree (harder to read):
```ruby
fits_into_octal?(value, length) ? to_octal(value, length) : to_base256(value, length)
```

(Tested with `print-width` of 100)

**Comment by kddnewton** [comment]
Sorry to be closing issues of yours left and right here, but I'm closing it for the same reason as here: https://github.com/ruby-syntax-tree/syntax_tree/issues/245#issuecomment-1370166915.

**Comment by davidtaylorhq** [comment]
For anyone that comes across this issue in future - for Discourse we've created this simple plugin which disables the automatic conversion of `if...else` to ternary: https://github.com/discourse/syntax_tree-disable_ternary

**Comment by kddnewton** [comment]
@davidtaylorhq I'd be happy to maintain that in Syntax Tree if you wanted to open a PR. That way I wouldn't accidentally break that if I move a module around.

**Comment by davidtaylorhq** [comment]
That would be great, thanks @kddnewton. I refactored the plugin to work similarly to the bundled quote/comma plugins and opened https://github.com/ruby-syntax-tree/syntax_tree/pull/250
