### ISSUE TITLE
Avoid having long call chains on same line

### ISSUE THREAD

**Issue by gschlager** [ruby-syntax-tree/syntax_tree#244]
I think stree should disregard the configured `print-width` and insert line breaks between chained method calls when the line length exceeds ~60 chars.

Okay:
```ruby
@pack_format ||= Header::FIELDS
  .values
  .map { |field| "a#{field[:length]}" }
  .join("")
```

A lot harder to read:
```ruby
@pack_format ||= Header::FIELDS.values.map { |field| "a#{field[:length]}" }.join("")
```

(Tested with `print-width` of 100)

**Comment by kddnewton** [comment]
As mentioned here: https://github.com/ruby-syntax-tree/syntax_tree/issues/245#issuecomment-1370166915, this is not feasible with syntax tree at the moment in a performant way. You can either configure your print width differently or ignore the node. 

Another option would be to write your own plugin to handle the formatting yourself in this case if you'd like.
