### ISSUE TITLE
README section for advanced usage

### ISSUE THREAD

**Issue by faraazahmad** [ruby-syntax-tree/syntax_tree#273]
PR #272 introduces very useful functionality but I understand its not in the use cases for the average gem consumer. I was thinking, does it make sense to have an advanced usage section in the README, this could also include the eventual translation to whitequark/parser when that is complete.

I only opened this issue because I thought this is a really great feature that syntax_tree comes with out of the box, but such "advanced" features are not very discoverable right now.

**Comment by kddnewton** [comment]
Yeah I'm certainly open to this, at the moment this stuff is undocumented because I'm not sure about the final API and it's relatively untested. So I'm going to wait a bit, but the features will be documented as soon as they're ready I promise.

**Comment by faraazahmad** [comment]
How can I help?
