### ISSUE TITLE
`NoMethodError location for "":String` in `on_regexp_add`

### ISSUE THREAD

**Issue by vinistock** [ruby-syntax-tree/syntax_tree#316]
I don't know what Ruby code triggers this error, but we caught it in the Ruby LSP's telemetry. It appears that `part` is an empty string and then invoking `location` on it breaks.

Happens on this line
https://github.com/ruby-syntax-tree/syntax_tree/blob/9129486860ac226439204cb23dcbbac060486f4f/lib/syntax_tree/parser.rb#L3137

**Comment by kddnewton** [comment]
Oh man I would love to know what triggered this. It is almost definitely a syntax error that is passing an unexpected type up the tree somehow. I'll see if I can replicate, but without the source I don't really know.

**Comment by kddnewton** [comment]
Okay, I totally believe you, but I cannot figure out a way to reproduce this at all. If you find the original source that did this, I can 100% fix it, but I don't want to add a type check unless I can add a test as well. I'm going to close for now since there's nothing really either of us can do.
