### ISSUE TITLE
Unexpected `nil` from `SyntaxTree.parse`

### ISSUE THREAD

**Issue by prikha** [ruby-syntax-tree/syntax_tree#357]
I've stumbled upon unexpected behaviour of `SyntaxTree#parse`

Actual behaviour: 

```rb
SyntaxTree.parse('/*/') #=> nil
```

Expected behaviour:

```rb
SyntaxTree.parse('/*/') #=> SyntaxTree::Parser::ParseError
```

It's not a bug, but more of an inconsistent interface, I expect it to return either a `Node` or raise an exception. And `nil` just doesn't give any information. I suggest raising exception in case of `parser.error?`

**Comment by prikha** [comment]
@kddnewton can you share some details, is the "new" parser already out or in the making?

**Comment by kddnewton** [comment]
The new parser is here: https://github.com/Shopify/yarp. The issue tracking its adoption is pinned and available here: https://github.com/ruby-syntax-tree/syntax_tree/issues/278.
