### ISSUE TITLE
Splitting up node.rb

### ISSUE THREAD

**Issue by dleavitt** [ruby-syntax-tree/syntax_tree#37]
On this and the prettier-ruby gem, I found that the "everything in one file" situation to be a bit of an obstacle to contributing and understanding what's going on. I notice you've started splitting up the different pieces - would you be open to a PR that puts each Node subclass in its own file?

**Comment by kddnewton** [comment]
I don't really want to move them into different files tbh. I _do_ want to move the entire formatting capability out into its own thing, and just keep the node definitions together. The thing is when they're in the same file it makes it really easy to make mass changes, as I have so far with the visitor pattern, pretty printing, and inheriting from the parent node class. It would have been harder doing that in different files.
