### ISSUE TITLE
Pretty-print regular expression options

### ISSUE THREAD

**Issue by flavorjones** [ruby-syntax-tree/syntax_tree#62]
Given the trivial program

```ruby
/asdf/
/asdf/i
/asdf/m
/asdf/x
/asdf/o
/asdf/imxo
```

the pretty-print for each of these regular expressions literals is identical:

```
(program
  (statements
    ((regexp_literal ((tstring_content "asdf"))),
      (regexp_literal ((tstring_content "asdf"))),
      (regexp_literal ((tstring_content "asdf"))),
      (regexp_literal ((tstring_content "asdf"))),
      (regexp_literal ((tstring_content "asdf"))),
      (regexp_literal ((tstring_content "asdf"))))))
```

even though they have different [options](https://ruby-doc.org/core-3.1.2/Regexp.html#class-Regexp-label-Options) (which are present in the AST node as part of the `ending` attribute).

I'm happy to submit a PR to change this behavior if you a) think it would be valuable, and b) would be so kind as to suggest the sexp structure you'd like to emit in this case.

**Comment by kddnewton** [comment]
Please do! I would add it to the `visit_regexp_literal` method with a `field` call. Something like `field("options", node.ending[1..-1])` should do the trick. (`ending` in this case is the close of the regex, so it could start with `/` or `}` or `>` or whatever else.)
