### ISSUE TITLE
Align control structure statements with method chaining

### ISSUE THREAD

**Issue by kddnewton** [ruby-syntax-tree/syntax_tree#63]
In case that some control structure statement chain methods, the indentations are not aligned.

ok:

```ruby
if condition
  #...
  value1
else
  #...
  value2
end.method1 do |this|
  #...
end.method2
```

ng:

```ruby
if condition
  #...
  value1
  else         # <- x
    #...
    value2
  end.method1  # <- x
  .method2　    # <- cause by the beginning of the line is a dot
  .method3 do
    #...
  end
  .method4
```

Originally from https://github.com/prettier/plugin-ruby/issues/1211.

**Comment by wenderjean** [comment]
I figured out that for this specific case if I do not consider those blocks as chained at [this](https://github.com/ruby-syntax-tree/syntax_tree/blob/main/lib/syntax_tree/node.rb#L2513) point the formater behaves like expected but I'm not sure yet how to create the condition.
```ruby
def self.chained?(node)
  case node
  in Call | MethodAddBlock[call: Call]
    true
  else
    false
  end
end
```

**Comment by kddnewton** [comment]
Closing this until it's rereported, as it's been open for a long time and I don't have the energy to get to it.
