### ISSUE TITLE
`config/rubocop.yml` not bundled inside the published gems

### ISSUE THREAD

**Issue by beauraF** [ruby-syntax-tree/syntax_tree#67]
The `config/rubocop.yml` file isn't published with the gems. 

This part of the doc is not doable:
```yml
inherit_gem:
  syntax_tree: config/rubocop.yml
```
<img width="307" alt="image" src="https://user-images.githubusercontent.com/12185788/167145257-b8422684-c721-462e-ae4f-a84c3ea2ad80.png">

Thanks a lot for your work! ✌️

**Comment by beauraF** [comment]
Ok, it was added after the last release. I'll close and wait next release :D

**Comment by kddnewton** [comment]
It's released now in v2.4.0
