### ISSUE TITLE
Configuring SyntaxTree formatting

### ISSUE THREAD

**Issue by elia** [ruby-syntax-tree/syntax_tree#76]
Any plans for allowing some level of configuration?

I'm trying to integrate it into [erb-formatter](https://github.com/nebulab/erb-formatter), and would really like to be able to configure staff like the max line width, or quotes, and so on.

OT: eventually I'd like to try writing a syntax tree plugin for ERB, but for now I'd like to be able to just use it for formatting bits of ruby code inside ERB files.

**Comment by kddnewton** [comment]
Yeah for sure. There's a configuration section in the README: https://github.com/ruby-syntax-tree/syntax_tree#configuration. Max line width is something you can pass to the formatter: `SyntaxTree::Formatter.new(source, [], 120)`.  Quotes can be configured through the predefined plugin in the README.

For more configuration, you would define whatever plugin you wanted. Then you can pass it through the CLI through the `--plugins` option. Basically you can write any Ruby code you like, so as much configurability as you want!

**Comment by elia** [comment]
Awesome thanks!
