### ISSUE TITLE
`plugin/single_quotes` changes strings that have single-quotes inside

### ISSUE THREAD

**Issue by boris-petrov** [ruby-syntax-tree/syntax_tree#86]
Using `@prettier/plugin-ruby` 3.1.2 and `syntax_tree` 2.6.0. A string like `x = "asd'qwe"` is changed to `x = 'asd\'qwe'` which I believe is worse. Is it possible to somehow configure `plugin/single_quotes`? Or change the default so it doesn't do that? :smile:

**Comment by nickhall** [comment]
For the record, I'm seeing the same behavior when double quotes are enclosed in single quotes, so something like `x = 'a "string"'` would become `x = "a \"string\""`

**Comment by boris-petrov** [comment]
I think I've also fixed this case with the PR.
